export const constants = {
  custommFeatures: [
    "All concrete and blockwork",
    "Complete Roofing",
    "All Windows, entrance & exit doors",
    "All mechanical piping",
    "All electrical piping & wiring",
    "Internal plastering only",
    "External plastering & painting",
  ],
  finishedFeatures: [
    "All concrete and blockwork",
    "Complete Roofing",
    "All Windows & doors",
    "All Sanitary fittings",
    "All electrical piping, wiring, fittings & accessories",
    "All floor finishing(tiling)",
    "POP Ceiling",
    "Internal plastering, pop screeding and painting",
    "External plastering and painting",
    "Kitchen fittings and fixtures",
  ],
  partly_finishedFeatures: [
    "All concrete and blockwork.",
    "Complete Roofing.",
    "All Windows, entrance, and exit doors.",
    "All mechanical piping.",
    "All electrical piping and wiring.",
    "Internal plastering.",
    "A room to be finished with floor tiling, ceiling, electrical fittings, and painting.",
    "A toilet to be completed with floor & wall tiling with plumbing fittings (WC and WHB).",
    "External plastering and painting.",
  ],
};
